name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest ]
        # The versions should contain (at least) the lowest requirement
        #    and a version that is more up to date.
        toit-version: [ latest ]
        include:
          - toit-version: latest
            version-name: new

    name: CI - ${{ matrix.os }} - ${{ matrix.version-name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ matrix.toit-version }}

      - name: Start httpbin - Linux
        if: runner.os == 'Linux'
        run: |
          docker pull kennethreitz/httpbin
          docker run -d -p 8765:80 kennethreitz/httpbin
          docker ps

      - name: Run cmake
        run:
          make rebuild-cmake

      - name: Enable httpbin tests - Linux
        if: runner.os == 'Linux'
        run: |
          docker ps
          cmake -DENABLE_HTTPBIN_TESTS=ON -DUSE_HTTPBIN_DOCKER=ON build

      # httpbin.org is overloaded at the moment, so if we are not running our
      # own in Docker, don't run it at all.
      - name: Enable httpbin tests - non-Linux
        if: runner.os != 'Linux'
        run: |
          cmake -DENABLE_HTTPBIN_TESTS=OFF build

      - shell: bash
        run: echo $PATH

      # Run ssh.
      - uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: "${{ secrets.NGROK_FLORIAN }}"
          SSH_PASS: "aoeuAOEU0"

      - name: Test
        run: |
          make test
